// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5PmBKBX1J_4TkzSsqclq2KGbYzL3Svzs',
    appId: '1:1069664606978:web:4fd780eeb05a3cb468001b',
    messagingSenderId: '1069664606978',
    projectId: 'gaurdpass',
    authDomain: 'gaurdpass.firebaseapp.com',
    storageBucket: 'gaurdpass.appspot.com',
    measurementId: 'G-P618QF7CST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfx5wXFofo14szyuCYfa0DGRUt1ormCIE',
    appId: '1:1069664606978:android:3142a12490d3631f68001b',
    messagingSenderId: '1069664606978',
    projectId: 'gaurdpass',
    storageBucket: 'gaurdpass.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoTnnNMRyga_W5MBhCfrgSUTE8QgdcbUE',
    appId: '1:1069664606978:ios:997d2afb0a681f9468001b',
    messagingSenderId: '1069664606978',
    projectId: 'gaurdpass',
    storageBucket: 'gaurdpass.appspot.com',
    iosBundleId: 'com.example.guard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoTnnNMRyga_W5MBhCfrgSUTE8QgdcbUE',
    appId: '1:1069664606978:ios:6162cc86734f831668001b',
    messagingSenderId: '1069664606978',
    projectId: 'gaurdpass',
    storageBucket: 'gaurdpass.appspot.com',
    iosBundleId: 'com.example.guard.RunnerTests',
  );
}
